import { useState } from "react";
import { recommendCrop } from "../services/cropService";
import { getWeather } from "../services/weatherService";
import jsPDF from "jspdf";

function CropRecommendation() {
  const [formData, setFormData] = useState({
    nitrogen: "",
    phosphorus: "",
    potassium: "",
    ph: "",
    city: "",
  });

  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [weatherInfo, setWeatherInfo] = useState(null);
  const [submittedData, setSubmittedData] = useState(null);
  const [recommendationTime, setRecommendationTime] = useState("");
  const [confidence, setConfidence] = useState("");
  const [riskLevel, setRiskLevel] = useState("");

  const cropImages = {
  rice: "https://cdn-icons-png.flaticon.com/512/2909/2909765.png",
  wheat: "https://cdn-icons-png.flaticon.com/512/766/766038.png",
  maize: "https://cdn-icons-png.flaticon.com/512/5346/5346178.png",
  cotton: "https://cdn-icons-png.flaticon.com/512/3159/3159310.png",
  coffee: "https://cdn-icons-png.flaticon.com/512/924/924514.png",
  jute: "https://cdn-icons-png.flaticon.com/512/766/766038.png",
};

const cropMessages = {
  rice: "Rice grows best in warm weather with high humidity.",
  wheat: "Wheat grows well in cool weather with moderate rainfall.",
  maize: "Maize is suitable for warm climates and fertile soil.",
  cotton: "Cotton grows best in warm and dry conditions.",
  coffee: "Coffee prefers mild temperatures and good rainfall.",
  jute: "Jute grows well in hot and humid climates.",
};

const cropTips = {
  rice: "💡 Tip: Keep the soil flooded during the growing season for better yield.",
  wheat: "💡 Tip: Use well-drained soil and avoid overwatering.",
  maize: "💡 Tip: Plant in fertile soil with full sunlight exposure.",
  cotton: "💡 Tip: Avoid excessive watering after flowering.",
  coffee: "💡 Tip: Grow in partial shade with regular irrigation.",
  jute: "💡 Tip: Jute grows best in warm and humid conditions with plenty of water.",
};

  // Handle Input Change
  const handleChange = (e) => {
    const { name, value } = e.target;

    setFormData({
      ...formData,
      [name]: name === "city" ? value : Number(value),
    });
  };

  // Handle Form Submit
  const handleSubmit = async (e) => {
    e.preventDefault();

    setLoading(true);
    setResult("");
    setWeatherInfo(null);

    try {
      // Get weather data
      const weather = await getWeather(formData.city);
      setWeatherInfo(weather);

      // Prepare crop data
      const cropData = {
        nitrogen: formData.nitrogen,
        phosphorus: formData.phosphorus,
        potassium: formData.potassium,
        ph: formData.ph,
        temperature: weather.main.temp,
        humidity: weather.main.humidity,
        rainfall: 100, // Temporary value
      };
      setSubmittedData(cropData);

      // Get crop recommendation
      const data = await recommendCrop(cropData);
      console.log(data.recommendation);
      setResult(data.recommendation);
      setConfidence("95%");
      if (weather.main.temp < 25) {
      setRiskLevel("🟢 Low");
      } else if (weather.main.temp <= 35) {
      setRiskLevel("🟡 Medium");
      } else {
      setRiskLevel("🔴 High");
      }
      setRecommendationTime(new Date().toLocaleString());

      setFormData({
      nitrogen: "",
      phosphorus: "",
      potassium: "",
      ph: "",
      city: "",
    });
    } catch (error) {
      console.error(error);
      alert(error.response?.data?.message || "Unable to get recommendation");
    } finally {
      // Always stop loading
      setLoading(false);
    }
  };

  const resetForm = () => {
  setResult("");
  setWeatherInfo(null);
  setSubmittedData(null);

  setFormData({
    nitrogen: "",
    phosphorus: "",
    potassium: "",
    ph: "",
    city: "",
  });
};

const cropName = result
  .replace(/[^\w\s]/g, "") // Remove emojis
  .trim()
  .toLowerCase();


  const downloadPDF = () => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text("AgriAI Crop Recommendation", 20, 20);

  doc.setFontSize(12);

  const cleanCrop = result.replace(/[^\w\s]/g, "").trim();
  const cleanRisk = riskLevel.replace(/[^\w\s]/g, "").trim();

  doc.text(`Crop: ${cleanCrop}`, 20, 40);
  doc.text(`City: ${weatherInfo?.name}`, 20, 50);
  doc.text(`Temperature: ${submittedData?.temperature} °C`, 20, 60);
  doc.text(`Humidity: ${submittedData?.humidity}%`, 20, 70);
  doc.text(`Soil pH: ${submittedData?.ph}`, 20, 80);
  doc.text(`Nitrogen: ${submittedData?.nitrogen}`, 20, 90);
  doc.text(`Phosphorus: ${submittedData?.phosphorus}`, 20, 100);
  doc.text(`Potassium: ${submittedData?.potassium}`, 20, 110);
  doc.text(`Confidence: ${confidence}`, 20, 120);
  doc.text(`Risk Level: ${cleanRisk}`, 20, 130)
  doc.text(`Generated: ${recommendationTime}`, 20, 140);
  
  doc.setFontSize(10);

  doc.text("----------------------------------------", 20, 160);

  doc.text(
  "Generated by AgriAI - Smart Farming Assistant",
  20,
  170
          );

   doc.text(
  "Thank you for using AgriAI!",
  20,
  180
          );

  doc.save("AgriAI_Crop_Recommendation.pdf");
};

  return (
    <div className="max-w-xl mx-auto mt-10 p-6 shadow-lg rounded-lg bg-white">
      <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
        🌾 Crop Recommendation
         </h1>
        {recommendationTime && (
        <p className="text-center text-gray-500 mt-2">
        🕒 Recommended on: {recommendationTime}
        </p>
)}
        {confidence && (
        <div className="flex justify-center mt-3">
         <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">
      ✅ Confidence: {confidence}
         </span>
        </div>
)}
        {riskLevel && (
        <div className="flex justify-center mt-3">
         <span className="bg-red-100 text-red-700 px-4 py-2 rounded-full font-semibold">
         Risk Level: {riskLevel}
         </span>
        </div>
)}
      

      <form onSubmit={handleSubmit} className="space-y-4">

        <input
          type="number"
          name="nitrogen"
          placeholder="Nitrogen"
          value={formData.nitrogen}
          onChange={handleChange}
          className="w-full border p-3 rounded"
          required
        />

        <input
          type="number"
          name="phosphorus"
          placeholder="Phosphorus"
          value={formData.phosphorus}
          onChange={handleChange}
          className="w-full border p-3 rounded"
          required
        />

        <input
          type="number"
          name="potassium"
          placeholder="Potassium"
          value={formData.potassium}
          onChange={handleChange}
          className="w-full border p-3 rounded"
          required
        />

        <input
          type="number"
          step="0.1"
          name="ph"
          placeholder="Soil pH"
          value={formData.ph}
          onChange={handleChange}
          className="w-full border p-3 rounded"
          required
        />

        <input
          type="text"
          name="city"
          placeholder="Enter City"
          value={formData.city}
          onChange={handleChange}
          className="w-full border p-3 rounded"
          required
        />

        <button
          type="submit"
          disabled={loading}
          className="w-full bg-green-700 text-white py-3 rounded hover:bg-green-800 transition disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          {loading ? "Loading..." : "Recommend Crop"}
        </button>

      </form>

      {result && weatherInfo && (
    <div className="mt-6 bg-linear-to-r from-green-100 to-green-50 border border-green-300 rounded-xl shadow-lg p-6">

    <div className="text-center mb-6">
      <h2 className="text-3xl font-bold text-green-700">
        🌾 Crop Recommendation
      </h2>

      <p className="text-green-600 mt-2">
        Based on your soil and weather conditions
      </p>

      <div className="mt-4 inline-block bg-green-700 text-white px-6 py-3 rounded-full text-2xl font-bold">
      🌱 {result}
      </div>

      <img
      src={
      cropImages[cropName] ||
      "https://cdn-icons-png.flaticon.com/512/628/628324.png"
          }
      alt={result}
     className="w-32 h-32 mx-auto mt-6 object-contain"
      />
  
     <p className="text-center text-gray-700 mt-4">
     {cropMessages[cropName] ||
     "This crop is suitable for the given conditions."}
      </p>
     <div className="mt-4 bg-yellow-100 border-l-4 border-yellow-500 p-4 rounded-lg">
     <p className="text-gray-800 font-medium">
     {cropTips[cropName] ||
     "💡 Follow good farming practices for the best yield."}
     </p>
     </div>
    </div>

    <div className="grid grid-cols-2 gap-4">

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">📍 City</h3>
        <p>{weatherInfo.name}</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🌡 Temperature</h3>
        <p>{submittedData?.temperature} °C</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">💧 Humidity</h3>
        <p>{submittedData?.humidity}%</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🧪 Soil pH</h3>
        <p>{submittedData?.ph}</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🌱 Nitrogen</h3>
        <p>{submittedData?.nitrogen}</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🧪 Phosphorus</h3>
        <p>{submittedData?.phosphorus}</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🪴 Potassium</h3>
        <p>{submittedData?.potassium}</p>
      </div>

      <div className="bg-white rounded-lg p-4 shadow">
        <h3 className="font-bold">🌧 Rainfall</h3>
        <p>{submittedData?.rainfall} mm</p>
      </div>

    </div>

  </div>
)}

<div className="mt-6 bg-green-50 border border-green-300 rounded-lg p-5">
  <h3 className="text-xl font-bold text-green-700 mb-3">
    📋 Recommendation Summary
  </h3>

  <ul className="space-y-2 text-gray-700">
    <li><strong>🌱 Crop:</strong> {result}</li>
    <li><strong>📍 City:</strong> {weatherInfo?.name}</li>
    <li><strong>🌡 Temperature:</strong> {submittedData?.temperature} °C</li>
    <li><strong>💧 Humidity:</strong> {submittedData?.humidity}%</li>
    <li><strong>🧪 Soil pH:</strong> {submittedData?.ph}</li>
    <li><strong>✅ Confidence:</strong> {confidence}</li>
    <li><strong>⚠️ Risk Level:</strong> {riskLevel}</li>
    <li><strong>🕒 Generated:</strong> {recommendationTime}</li>
  </ul>
</div>
<div className="mt-6 text-center">
  <button
    onClick={resetForm}
    className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition"
  >
    🔄 Try Another Recommendation
  </button>
</div>
<div className="mt-6 text-center">
  <button
    onClick={downloadPDF}
    className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition"
  >
    📄 Download Recommendation PDF
  </button>
</div>
      
    </div>
  );
}

export default CropRecommendation;